In [20]:
import tensorflow as tf
import numpy as np

1/ Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [13]:
scalar = tf.constant(1)
vector = tf.constant([1,2])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[7,8]]])

2/ Find the shape, rank and size of the tensors you created in 1.

In [16]:
print(scalar.ndim)
print(scalar.shape)
print(tf.size(scalar))

0
()
tf.Tensor(1, shape=(), dtype=int32)


In [17]:
print(vector.ndim)
print(vector.shape)
print(tf.size(vector))

1
(2,)
tf.Tensor(2, shape=(), dtype=int32)


In [18]:
print(matrix.ndim)
print(matrix.shape)
print(tf.size(matrix))

2
(2, 2)
tf.Tensor(4, shape=(), dtype=int32)


In [19]:
print(tensor.ndim)
print(tensor.shape)
print(tf.size(tensor))

3
(2, 2, 2)
tf.Tensor(8, shape=(), dtype=int32)


3/ Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [25]:
np1 = np.random.randint(2,size = 1500)
np2 = np.random.randint(2,size = 1500)

t1 = tf.constant(np1,shape = (5,300))
t2 = tf.constant(np2,shape = (5,300))

In [27]:
t1

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[1, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 1, 1]])>

4/ Multiply the two tensors you created in 3 using matrix multiplication.

In [29]:
tf.matmul(t1,tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[72, 65, 75, 69, 75],
       [78, 65, 74, 74, 79],
       [77, 69, 85, 72, 83],
       [74, 63, 71, 65, 83],
       [78, 67, 73, 63, 76]])>

5/ Multiply the two tensors you created in 3 using dot product.

In [31]:
tf.tensordot(t1,tf.transpose(t2),axes = 1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[72, 65, 75, 69, 75],
       [78, 65, 74, 74, 79],
       [77, 69, 85, 72, 83],
       [74, 63, 71, 65, 83],
       [78, 67, 73, 63, 76]])>

6/ Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [36]:
rand = tf.random.Generator.from_seed(42)
tensor = rand.uniform(minval = 0,maxval = 1, shape = (244,244,3))
tensor

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.5262728 , 0.81607926, 0.19863963],
        [0.12317097, 0.5962993 , 0.07343638],
        [0.18146193, 0.26921892, 0.71201587]],

       [[0.31422472, 0.15571809, 0.59350574],
        [0.21187031, 0.06828582, 0.6658218 ],
        [0.02978647, 0.07853341, 0.4606458 ],
        ...,
        [0.06088531, 0.46336675, 0.7801064 ],
        [0.9507414 , 0.5222603 , 0.3588164 ],
        [0.81559753, 0.8372953 , 0.12298954]],

       [[0.7429452 , 0.4534787 , 0.17754185],
        [0.40219545, 0.45187676, 0.04423535],
        [0.03875005, 0.95273983, 0.84132195],
        ...,
        [0.7266562 , 0.01516867, 0.62724495],
        [0.18723834, 0.26536012, 0.63592315],
        [0.40533996, 0.5552931 , 0.44928002]],

       ...,

       [[0.9760084 , 0.2899176 , 0.12237167],
        [0.26

7/ Find the min and max values of the tensor you created in 6 along the first axis.

In [37]:
min = tf.reduce_min(tensor)
min

<tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>

In [38]:
max = tf.reduce_min(tensor)
max

<tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>

8/ Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [39]:
tensor = tf.random.uniform(minval = 0,maxval = 1, shape = [1,244,244,3])
tensor

<tf.Tensor: shape=(1, 244, 244, 3), dtype=float32, numpy=
array([[[[0.16513085, 0.9014813 , 0.6309742 ],
         [0.4345461 , 0.29193902, 0.64250207],
         [0.9757855 , 0.43509948, 0.6601019 ],
         ...,
         [0.46882296, 0.78068674, 0.253474  ],
         [0.03136981, 0.464054  , 0.10266209],
         [0.7231915 , 0.05431902, 0.7268468 ]],

        [[0.4520818 , 0.38846374, 0.3653822 ],
         [0.6141635 , 0.14993382, 0.9539468 ],
         [0.4636047 , 0.37832975, 0.7151705 ],
         ...,
         [0.61517894, 0.28339207, 0.9293091 ],
         [0.5006882 , 0.03120244, 0.34679234],
         [0.8630954 , 0.25210488, 0.54442596]],

        [[0.46761072, 0.1564151 , 0.5438162 ],
         [0.34678483, 0.3413955 , 0.13692296],
         [0.9267609 , 0.8339577 , 0.45189488],
         ...,
         [0.7810453 , 0.36938024, 0.28597903],
         [0.5209588 , 0.7594497 , 0.23387086],
         [0.2120825 , 0.7314757 , 0.11759007]],

        ...,

        [[0.39344025, 0.86821747, 

In [40]:
tensor_squeezed = tf.squeeze(tensor)
tensor_squeezed

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.16513085, 0.9014813 , 0.6309742 ],
        [0.4345461 , 0.29193902, 0.64250207],
        [0.9757855 , 0.43509948, 0.6601019 ],
        ...,
        [0.46882296, 0.78068674, 0.253474  ],
        [0.03136981, 0.464054  , 0.10266209],
        [0.7231915 , 0.05431902, 0.7268468 ]],

       [[0.4520818 , 0.38846374, 0.3653822 ],
        [0.6141635 , 0.14993382, 0.9539468 ],
        [0.4636047 , 0.37832975, 0.7151705 ],
        ...,
        [0.61517894, 0.28339207, 0.9293091 ],
        [0.5006882 , 0.03120244, 0.34679234],
        [0.8630954 , 0.25210488, 0.54442596]],

       [[0.46761072, 0.1564151 , 0.5438162 ],
        [0.34678483, 0.3413955 , 0.13692296],
        [0.9267609 , 0.8339577 , 0.45189488],
        ...,
        [0.7810453 , 0.36938024, 0.28597903],
        [0.5209588 , 0.7594497 , 0.23387086],
        [0.2120825 , 0.7314757 , 0.11759007]],

       ...,

       [[0.39344025, 0.86821747, 0.84223247],
        [0.80

9/ Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [42]:
tensor = tf.range(10)
tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [43]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

10/ One-hot encode the tensor you created in 9.

In [45]:
one_hot = tf.one_hot(tensor,depth = tf.size(tensor).numpy())
one_hot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## Extra Curriculum 

- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    - How would you calculate your grocery bill for the month and for the year using tensors?

In [52]:
price = tf.constant([0.5, 0.2,1.2],shape = (1,3),dtype = tf.float32)
price

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.5, 0.2, 1.2]], dtype=float32)>

In [53]:
quantity = tf.constant([10,20,23],shape = (3,1),dtype = tf.float32)
quantity

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [23.]], dtype=float32)>

In [54]:
total = price @ quantity
total

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[36.6]], dtype=float32)>