# Concepts

In this noteebook, we're going to cover some of the most fundamentals concepts of tensors using tensorflow

    - Introduction to tensors
    - Getting infomation from tensors
    - Manipulating tensors
    - Tensors & numpy
    - Using @tf.function ( a way to speed up your python function )
    - Using GPU (Graphic processing unit) or TPU (Tensor processing unit) with tensorflow
    - Excercises to try yourself

In [2]:
# install tensorflow on terminal
# !pip install tensorflow
# pip3 install tensorflow

In [6]:
# import tensorflow
import tensorflow as tf
print ("Your tensorflow version: " + str(tf.__version__))
print (f"Your tensorflow version: {tf.__version__}")
print ("Your tensorflow version: {0}".format(tf.__version__))
print ("Your tensorflow version:",tf.__version__)

Your tensorflow version: 2.6.0
Your tensorflow version: 2.6.0
Your tensorflow version: 2.6.0
Your tensorflow version: 2.6.0


## tf.constant

In [9]:
# create tensors with tf.constant()
scalar = tf.constant(7)
print(type(scalar))
scalar

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# check the number of dimensions of a tensor (ndim stantd for number of dimensions)
scalar.ndim

0

In [12]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [13]:
vector.ndim

1

In [14]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [15]:
matrix.ndim

2

In [17]:
error = tf.constant([[1,2,4],[1,2]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [21]:
# create another matrix specify type
# another_matrix = tf.constant([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]],dtype = tf.float16)
another_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [23]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [27]:
another_matrix = tf.constant([[10.,9.,8.],[7.,6.,5.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  9.,  8.],
       [ 7.,  6.,  5.]], dtype=float16)>

In [28]:
# what is the number dimensions of another_matrix
another_matrix.ndim

2

In [34]:
tensor = tf.constant([ [[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                      
                       [[10,11,12],
                        [13,14,15],
                        [16,17,18]],
                       
                       [[19,20,21],
                        [22,23,24],
                        [25,26,27]],
                      
                      [[28,29,30],
                        [31,32,33],
                        [34,35,36]]
                     
                     ] )
tensor

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])>

In [35]:
tensor.ndim

3

In [37]:
# tensor number, rows, columns
another_tensor = tf.constant([ [[1,2],
                        [4,5],
                        [7,8]],
                      
                       [[10,11],
                        [13,14],
                        [16,17]],
                       
                       [[19,20],
                        [22,23],
                        [25,26]],
                      
                      [[28,29],
                        [31,32],
                        [34,35]]
                     
                     ] )
another_tensor

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]],

       [[28, 29],
        [31, 32],
        [34, 35]]])>

In [39]:
another_tensor = tf.constant([
                [[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]]
                ])
another_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

What we have created so far:
* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array numbers
* Tensor: an n-dimensional array of numbers (when n can be any number 0-dim is number,1-dim is vector,2-dim is a matrix

## tf.Variable

In [43]:
# create a changeable tensor
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [44]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [45]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [47]:
# let's try to change one of the element in our changeable tensor
changeable_tensor[0] = 7 

TypeError: 'ResourceVariable' object does not support item assignment

In [50]:
# How about this way
changeable_tensor[0].assign(7) # varlue must be the same type of the initial type

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [52]:
# How about unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 **Note:** Rarely in practice you will need to decide whether to use `tf.constant` or `tf.Variable` to create tensors,
as TensorFlow does this for you, if in doubt, use `tf.constant' and change it later if needed

## Creating random tensors
Random tensors are tensors of some abitrary size which contain random numbers

In [73]:
## let create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1

In [74]:
for i in dir(random_1):
    if "_" not in i:
        print(i)

algorithm
binomial
key
normal
reset
skip
split
state
uniform


In [75]:
normal_1 = random_1.normal(shape = (3,2))
normal

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [76]:
uniform = random_1.uniform(shape =  (3,2))
uniform

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7647915 , 0.03845465],
       [0.8506975 , 0.20781887],
       [0.711869  , 0.8843919 ]], dtype=float32)>

In [77]:
# let create another random with the same seed
random_2 = tf.random.Generator.from_seed(42)
normal_2 = random_2.normal(shape= (3,2))
normal_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [78]:
normal_1 == normal_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of elements in a tensor

In [111]:
# shuffle a tensor (valuable for when you want to shuffle your data so inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,2],
                           [3,4],
                           [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 3,  4],
       [ 2,  5]])>

In [112]:
not_shuffled.ndim

2

In [123]:
# shuffle out non-shuffled tensors, randomly shuffle the first dimension
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed = 1)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 2,  5],
       [ 3,  4]])>

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
To illustrate the user-visible effects, consider these examples:

If neither the global seed nor the operation seed is set, we get different results for every call to the random op and every re-run of the program:

In [126]:
dir(tf.function)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__original_wrapped__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__wrapped__',
 '_tf_decorator']

In [127]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)


In [128]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


In [136]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [138]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [140]:
# global seed
tf.random.set_seed(1234)

@tf.function
def f():
    a = tf.random.uniform([1])
    b = tf.random.uniform([1])
    return a,b

@tf.function
def g():
    a = tf.random.uniform([1])
    b = tf.random.uniform([1])
    return a,b

print(f())
print(g())
#dir(tf.function)

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [159]:
# operation seed
print(tf.random.uniform([1],seed = 1))
print(tf.random.uniform([1],seed = 1))

tf.Tensor([0.75075316], shape=(1,), dtype=float32)
tf.Tensor([0.12093925], shape=(1,), dtype=float32)


In [175]:
# operation seed
'''
The reason we get 'A2' instead 'A1' on the second call of tf.random.uniform above is because the same tf.random.uniform kernel
(i.e. internal representation) is used by TensorFlow for all calls of it with the same arguments, and the kernel maintains an internal counter which is incremented every time it is executed, 
generating different results.
'''
print(tf.random.uniform([1],seed = 1))
print(tf.random.uniform([1],seed = 1))

tf.Tensor([0.92801344], shape=(1,), dtype=float32)
tf.Tensor([0.92192256], shape=(1,), dtype=float32)


In [172]:
print(tf.random.uniform([1],seed = 1))

tf.Tensor([0.8399737], shape=(1,), dtype=float32)


In [177]:
'''
When multiple identical random ops are wrapped in a tf.function, 
their behaviors change because the ops no long share the same counter
'''
@tf.function
def foo():
    a = tf.random.uniform([1],seed = 1)
    b = tf.random.uniform([1],seed = 1)
    return a,b

print(foo())
print(foo())

@tf.function
def bar():
    a = tf.random.uniform([1])
    b = tf.random.uniform([1])
    return a,b

print(bar())
print(bar())

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


In [180]:
tf.random.set_seed(1)
@tf.function
def foo():
    a = tf.random.uniform([1],seed = 1)
    b = tf.random.uniform([1],seed = 1)
    return a,b

print(foo())
print(foo())

@tf.function
def bar():
    a = tf.random.uniform([1])
    b = tf.random.uniform([1])
    return a,b

print(bar())
print(bar())

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05554414], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05554414], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8388307], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8388307], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.81269646], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05554414], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5272893], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8388307], dtype=float32)>)


In [182]:
original = tf.constant([[1,2],[3,4],[4,5]])
original

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [186]:
shuffled = tf.random.shuffle(original)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [3, 4],
       [1, 2]])>

In [187]:
shuffled = tf.random.shuffle(original)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [195]:
shuffled = tf.random.shuffle(original,seed =1)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [3, 4]])>

In [196]:
shuffled = tf.random.shuffle(original,seed =1)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [3, 4],
       [1, 2]])>

In [197]:
tf.random.set_seed(1)
shuffled = tf.random.shuffle(original)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [3, 4]])>

In [198]:
tf.random.set_seed(1)
shuffled = tf.random.shuffle(original)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [3, 4]])>

## Other way to create tensors

In [200]:
# create a tensor all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [201]:
# create a tensors all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

the main difference between Numpy arrays and tensorflow tensors is that tensors can be run on a GPU computing

In [203]:
# turn numpy array into tensorflow tensor
# capital for matrix and tensor
# non-
import numpy as np 
numpy_A =  np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [204]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [205]:
A.ndim

1

In [206]:
B = tf.constant(numpy_A,shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [207]:
B.ndim

3