## Getting information from tensors


In [1]:
import tensorflow as tf

Getting more information from tensors, when dealing with tensors you probably want to be aware with the following attributes:

* Shape
* Rank
* Axis or dimension
* Size

![tensor-infomation](./images/00-tensor-informantion.jpg)

In [4]:
tensor = tf.constant([ [[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                      
                    [[11,12,13],
                     [14,15,16],
                     [17,18,19]]
                     
                     ],dtype = tf.float16)
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]]], dtype=float16)>

In [13]:
print(f"tensor.shape: {tensor.shape}")
print(f"tensor.ndim: {tensor.ndim}")
print(f"tf.size(tensor): {tf.size(tensor)}")

tensor.shape: (2, 3, 3)
tensor.ndim: 3
tf.size(tensor): 18


In [17]:
tensor[1]

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]], dtype=float16)>

In [18]:
tensor[1,0]

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([11., 12., 13.], dtype=float16)>

In [19]:
tensor[1,0,0]

<tf.Tensor: shape=(), dtype=float16, numpy=11.0>

In [20]:
tensor[0,:,1]

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2., 5., 8.], dtype=float16)>

In [22]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
#index
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
print(f"rank_4_tensor.shape: {rank_4_tensor.shape}")
print(f"rank_4_tensor.ndim: {rank_4_tensor.ndim}")
print(f"tf.size(rank_4_tensor): {tf.size(rank_4_tensor)}")

rank_4_tensor.shape: (2, 3, 4, 5)
rank_4_tensor.ndim: 4
tf.size(rank_4_tensor): 120


In [29]:
# get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of element in our tensor:",tf.size(rank_4_tensor))
print("Total number of element in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of element in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of element in our tensor: 120


## indexing tensors
Tensors can be indexed just like Python lists

In [32]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
# Get the first element from each index ecept for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
# Get the first element from each index ecept for the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [39]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [40]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [43]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
#rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [44]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [45]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [46]:
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

## Manipulating tensors (tensor operations)

**Basic operations** `+`,`-`,`*`,`/`

In [49]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [50]:
tensor = tensor +10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [51]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [58]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [53]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.7],
       [1.3, 1.4]])>

In [54]:
# we can you the tensorflow built-in function
dir(tf.math)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'abs',
 'accumulate_n',
 'acos',
 'acosh',
 'add',
 'add_n',
 'angle',
 'argmax',
 'argmin',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'bessel_i0',
 'bessel_i0e',
 'bessel_i1',
 'bessel_i1e',
 'betainc',
 'bincount',
 'ceil',
 'confusion_matrix',
 'conj',
 'cos',
 'cosh',
 'count_nonzero',
 'cumprod',
 'cumsum',
 'cumulative_logsumexp',
 'digamma',
 'divide',
 'divide_no_nan',
 'equal',
 'erf',
 'erfc',
 'erfcinv',
 'erfinv',
 'exp',
 'expm1',
 'floor',
 'floordiv',
 'floormod',
 'greater',
 'greater_equal',
 'igamma',
 'igammac',
 'imag',
 'in_top_k',
 'invert_permutation',
 'is_finite',
 'is_inf',
 'is_nan',
 'is_non_decreasing',
 'is_strictly_increasing',
 'l2_normalize',
 'lbeta',
 'less',
 'less_equal',
 'lgamma',
 'log',
 'log1p',
 'log_sigmoid',
 'log_softmax',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'maximum',
 '

In [59]:
# speed up your calculation with tensorflow built-in function
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

**Matrix multiplication**
The most operation in machine learning

In [61]:
#tf.linalg.matmul
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]])>

In [62]:
# matix multiplication with python operator "@"
tensor1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [63]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [65]:
tensor2 @ tensor1

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,3] 0 0 [Op:MatMul]

In [68]:
tensor2 = tf.reshape(tensor2,shape= (2,3))
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]])>

In [69]:
# Reshape and multiply again
tensor2 @ tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 34, 38],
       [38, 40, 60]])>

In [70]:
tensor1.shape

TensorShape([3, 3])

In [71]:
tensor = tf.constant([[1,2],[3,4],[5,6]])

tf.matmul(tensor, tf.reshape(tensor,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [75]:
# transpose tensor
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [77]:
tf.reshape(tensor,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [76]:
tensor_t = tf.transpose(tensor)
tensor_t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

**The dor product**

Matrix multiplication is also referred to as the fot product

`tf.matmul`

`tf.tensordot`

In [78]:
# Perform the fot product on X and Y (requires X or Y to be transposed)
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

In [81]:
dir(Y)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',


In [84]:
tf.tensordot(tf.transpose(X),Y, axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [92]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [90]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]])>

In [91]:
 tf.reshape(Y,shape= (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [89]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [88]:
tf.matmul(X, tf.reshape(Y,shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

almost calculation we do with traspose, not reshape

## Changing the datatype of the tensor

In [100]:
# Create a new tensor with default the datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype 

tf.float32

In [101]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [102]:
# change from float32 to float16 (reduced the precision)
D = tf.cast(B,dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [103]:
# Change from int32 to float32
E = tf.cast(C,dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [104]:
# Change from float32 into int32
F = tf.cast(B,dtype = tf.int32)
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

* Get the absolute of the tensor
* Get the minimum of the tensor
* Get the maximum of the tensor
* Get the mean of the tensor
* Get the sum of the tensor

In [106]:
# Get the absolute value
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [108]:
E = tf.abs(D)
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [110]:
import numpy as np

In [111]:
# Create a random tensor with value between 0,100
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([79, 36, 33, 98, 10, 88, 86,  3, 86, 76, 82, 42, 22, 46,  4, 95, 66,
       97, 90, 46, 91, 87, 87, 35, 19, 81, 16, 56, 21, 32, 12, 22, 14, 38,
       10, 27, 25, 44, 81,  6, 51,  7, 61, 19, 59, 54,  0, 27, 45, 89])>

In [112]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [113]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [114]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [116]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2401>

In [135]:
import tensorflow_probability as tfp

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.7; Detected an installation of version 2.6.0. Please upgrade TensorFlow to proceed.

In [7]:
#reload your notebook
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

In [8]:
tf.__version__

'2.7.0'

In [9]:
tfp.__version__

'0.15.0'

In [21]:
E = tf. constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 3, 94, 25, 14, 13, 68, 47, 62, 14, 82, 59, 15, 88, 50, 55, 43, 57,
       78, 40, 63, 33, 73, 32, 95, 84, 79, 31, 29, 61,  9, 97, 96, 81, 66,
       56, 12, 13, 84, 90, 75, 96, 35, 49,  5, 87, 64, 12, 34,  5, 92])>

In [22]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=894>

In [23]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.89933>

In [24]:
# variance
var = tf.reduce_sum( (E - tf.reduce_mean(E))**2 )/(tf.size(E))
var

<tf.Tensor: shape=(), dtype=float64, numpy=894.78>

In [25]:
# standard deviation
d = tf.math.sqrt(var)
d

<tf.Tensor: shape=(), dtype=float64, numpy=29.91287348283344>

In [1]:
import tensorflow as tf 
import numpy as np

In [3]:
E = tf.constant(np.random.randint(1,100,size = 50))

In [5]:
tf.math.reduce_std(tf.cast(E,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.309855>

In [6]:
tf.math.reduce_variance(tf.cast(E,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=859.0676>

## Find the positional maximum and minimum

In [46]:
# Create a new tensor for finding positional minimum and maxmimum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [47]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [49]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [52]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [48]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [54]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [53]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing all the tensor (removing all single dimensions)

In [56]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [57]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [58]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [59]:
G_squeezed.shape

TensorShape([50])

## One-hot encoding tensors

In [61]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green,blue,purple

# One hot encode our list of indices
tf.one_hot(some_list,depth = len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [65]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth= 4, on_value = 'bar',off_value = 'foo')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'bar', b'foo', b'foo', b'foo'],
       [b'foo', b'bar', b'foo', b'foo'],
       [b'foo', b'foo', b'bar', b'foo'],
       [b'foo', b'foo', b'foo', b'bar']], dtype=object)>

## Squaring,log,square root

In [70]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [71]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [73]:
tf.sqrt(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [75]:
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and numpy

tensorflow interacts beautifully with Numpy arrays

In [78]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [79]:
# Convert out tensor back to Numpy array
j = np.array(J)
print(j)
print(type(j))

[ 3.  7. 10.]
<class 'numpy.ndarray'>


In [80]:
j = J.numpy()
print(type(j))

<class 'numpy.ndarray'>


In [81]:
# The default types of each are slightly different if you convert a numpy array into tensor, they may have dtype differnent
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)