# Tensor Basic

- Rank 0: Scalar (0-dim)

- Rank 1: Vecor (1-dim)

- Rank 2: Matrix (2-dim)

- Rank 3: Tensor (3-dim)

- Rank 4: Tensor (4-dim)

In [1]:
import tensorflow as tf
import os

In [2]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # ignore the GPU warning

In [3]:
tf.__version__

'2.6.0'

In [36]:
# check physical GPU
physical_devices = tf.config.list_physical_devices('GPU')
physical_devices

[]

In [37]:
tf.config.experimental.set_memory_growth(physical_devices[0],True)

IndexError: list index out of range

## Initialization of tensors

In [6]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [7]:
x = tf.constant(4.0)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [8]:
x = tf.constant(4,shape=(1,1),dtype = tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [9]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [10]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
x = tf.zeros((2,3)) # (row,column)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
x = tf.eye(3) # I for the identity matrix (eye)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [13]:
x = tf.random.normal((3,3),mean=0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.28552875, -1.0585741 , -0.14701478],
       [ 1.1437157 ,  1.040358  ,  0.5862582 ],
       [ 1.8993187 ,  0.96593386,  0.542921  ]], dtype=float32)>

In [15]:
x = tf.random.uniform((1,3),minval = 0,maxval =1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.17080069, 0.684049  , 0.0966475 ]], dtype=float32)>

In [16]:
x = tf.range(9) # vector
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [17]:
x = tf.range(start=1,limit=10,delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [18]:
# tf.float(16,32,64) tf.int(8,16,32,64), tf.bool
x = tf.cast(x,dtype=tf.float64)
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

## Mathematical Operations

In [20]:
X = tf.constant([1,2,3])
Y = tf.constant([7,8,9])
print(X)
print(Y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [23]:
Z = tf.add(X,Y)
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 10, 12])>

In [24]:
Z = X + Y
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 10, 12])>

In [25]:
Z = tf.subtract(X,Y)
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -6, -6])>

In [27]:
Z = X - Y
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -6, -6])>

In [28]:
Z = tf.divide(X,Y)
Z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.14285714, 0.25      , 0.33333333])>

In [30]:
Z = tf.multiply(X,Y)
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 16, 27])>

In [31]:
Z = X * Y
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 16, 27])>

In [32]:
# dot product
Z = tf.tensordot(X,Y,axes = 1)
Z

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [34]:
Z = tf.reduce_sum(X*Y,axis =0)
Z

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [35]:
Z = X* 5
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10, 15])>

In [38]:
# matrix multiply
A = tf.random.normal((2,3)) # (row,column)
B = tf.random.normal((3,4)) # (row,column)
Z = tf.matmul(A,B)
Z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.68652135,  1.2643292 ,  0.76495427, -0.72689617],
       [ 0.6453803 ,  0.73054576, -0.18627205, -0.5691679 ]],
      dtype=float32)>

In [39]:
Z  = A @ B
Z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.68652135,  1.2643292 ,  0.76495427, -0.72689617],
       [ 0.6453803 ,  0.73054576, -0.18627205, -0.5691679 ]],
      dtype=float32)>

## Indexing

In [43]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:]) # print all
print(x[1:]) # print all except the first one
print(x[1:3]) # print from 1th to 3th-1
print(x[::2]) # print with step = 2
print(x[::-1]) # print with revert other

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [44]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [47]:
x= tf.constant([[1,2],[3,4],[4,6]])
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [4 6]], shape=(3, 2), dtype=int32)


In [48]:
print(x[0,:]) # print first row all column

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [49]:
print(x[0:2,:]) # print from first row to 1th row all column

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshape

In [51]:
x= tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [52]:
x =tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [53]:
x= tf.range(20)
x

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])>

In [56]:
x = tf.reshape(x,(10,2))
x

<tf.Tensor: shape=(10, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])>

In [57]:
x = tf.transpose(x,perm=[1,0]) # work for multi dim
x

<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])>